Vagrant.configure("2") do |config|
    
  config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: false
  config.puppet_install.puppet_version = '6.24.0'
  config.vm.provision :puppet
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
  
  config.vm.define "appserver" do |appserver|
  
	appserver.vm.provider :digital_ocean do |provider, override|
	  override.ssh.private_key_path = "C:\\Users\\Ralle\\.ssh\\id_rsa"
	  override.vm.box = 'digital_ocean'
	  override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	  override.nfs.functional = false
	  override.vm.allowed_synced_folder_types = [:rsync]
	  provider.token = ENV['DIGITAL-OCEAN-TOKEN']
	  provider.image = 'ubuntu-18-04-x64'
	  provider.region = 'nyc1'
	  provider.size = 's-1vcpu-1gb'
	  provider.setup = false
	  provider.ssh_key_name = "mykey"
	end
	
	appserver.vm.provision "puppet" do |puppet|
	  puppet.environment = "appserver"
	  puppet.environment_path = "./environments"
	  puppet.options = "--verbose --debug"
	end	
	
	appserver.vm.provider "virtualbox" do |vb|
	  appserver.vm.box = "bento/ubuntu-18.04"
	  vb.name = "appserver"
	end
  end

  config.vm.define "dbserver" do |dbserver|
    
	dbserver.vm.provider :digital_ocean do |provider, override|
	  override.ssh.private_key_path = "C:\\Users\\Ralle\\.ssh\\id_rsa"
	  override.vm.box = 'digital_ocean'
	  override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	  override.nfs.functional = false
	  override.vm.allowed_synced_folder_types = [:rsync]
	  provider.token = ENV['DIGITAL-OCEAN-TOKEN']
	  provider.image = 'ubuntu-18-04-x64'
	  provider.region = 'nyc1'
	  provider.size = 's-1vcpu-1gb'
	  provider.setup = false
	  provider.ssh_key_name = "mykey"
	end
	
	dbserver.vm.provision "puppet" do |puppet|
	  puppet.environment = "dbserver"
	  puppet.environment_path = "./environments"
	  puppet.options = "--verbose --debug"
	end	
	
	dbserver.vm.provider "virtualbox" do |vb|
	  dbserver.vm.box = "bento/ubuntu-18.04"
	  vb.name = "dbserver"
	end
  end
end